config/routes.rb
Catlindesign::Application.routes.draw do

  root :to => "main#index"
  
  resources :areas do
    resources :pages
  end
  
  resources :people
  resources :albums do
    resources :pictures
  end
  
  get "admin" => "admin#index"
  
  # For logging in etc.
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :show
    delete 'logout' => :destroy
  end
  
  namespace :admin do |admin|
    resources :people
    resources :users
    resources :albums do
      resources :pictures
    end
    resources :areas do
      resources :pages
    end
  end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => "welcome#index"

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/models/album.rb
class Album < ActiveRecord::Base
  has_many :pictures
end

app/models/area.rb
class Area < ActiveRecord::Base
  has_many :pages
  
  validates_uniqueness_of :name

  def self.[](name)
    self.find_by_name(name)
  end
  
  def to_param
    "#{self.id}-#{name.underscore}"
  end
end

app/models/copy_fragment.rb
class CopyFragment < ActiveRecord::Base
end

app/models/page.rb
class Page < ActiveRecord::Base
  belongs_to :area
end

app/models/person.rb
class Person < ActiveRecord::Base
  def to_param
    self.id.to_s + "-" + self.name.gsub(/[^a-zA-Z]/, "").underscore
  end
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :album
  
  has_attached_file :photo, styles: {thumb: "150x150#", large: "500x500#"}
  validates_attachment :photo, content_type: { content_type: ["image/jpeg", "image/gif", "image/png"]}
  
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  has_secure_password
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout 'admin'
  
  before_action :authorize
  
  def index
  end
  
  private
  
  def authorize
    puts session[:user_id]
    puts "Authorised with session user id above"
    unless User.find_by(id: session[:user_id])
      redirect_to login_url, notice: "Please log in."
    end
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    @albums = Album.all
  end
  
  def show
    @album = Album.find(params[:id])
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  make_resourceful do
    actions :index, :show
    
    belongs_to :area
  end
  
  def subnav
    @area.pages.collect do |page|
      {:partial => "page", :locals => {:page => page}}
    end
  end
  helper_method :subnav
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  make_resourceful do
    actions :show
  end
  
  def index
    redirect_to Person.first
  end
  
  def subnav
    current_objects.collect do |person|
      {:partial => "person", :locals => {:person => person}}
    end
  end
  helper_method :subnav
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def show
    @picture = Picture.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(name: params[:name])
    if user and user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to admin_path
    else
      redirect_to login_url, alert: "Incorrect username or password."
    end
  end
  
  def show
    reset_session
  end

  def destroy
    # puts "LOGGING OUT"
    # cookies.delete :_catlindesign_session
    reset_session
    # puts "Session user_id = " + session[:user_id]
    redirect_to logout_url
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    renderer = Redcarpet::Render::HTML.new()
    markdown = Redcarpet::Markdown.new(renderer)

    markdown.render(text).html_safe
  end
  
  # Macro printing method for all sidebars sitewide.
  # in each controller... override the method "sidebar" to return an array of strings
  def print_subnav
    sidebar_list = subnav
    if sidebar_list.any?
      haml_tag :div, :class => "subnav" do
        haml_tag :ul do
          sidebar_list.each do |item|
            if item.is_a? Hash
              item = render(item)
            end
            haml_concat item
          end
        end
      end
    end
  end
  
  def subnav
    []
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.haml
%p 
  Welcome to the admin section of the site.

app/views/admin/pages/_form.haml
.widget
  %label Page Name
  = text_field :page, :name
.widget
  ~ text_area :page, :body
%br/

app/views/admin/pages/edit.haml
%h1 Editing page

= form_tag(admin_area_page_path(@area, @page), :method => :put) do |f| 
  = render :partial => "form"
  %p= submit_tag "Update"

= link_to 'Show Public Version', [@area, @page]
|
= link_to 'Back', admin_area_pages_path(@area)

app/views/admin/pages/index.haml
%h1 
  Listing pages in
  = @area.name

%table
  %tr

  - for page in @pages
    %tr
      %td.name= page.name
      %td.show= link_to 'Show Public', [@area, page]
      %td.show= link_to 'Edit', edit_admin_area_page_path(@area, page)  
      %td.delete= link_to 'Destroy', admin_area_page_path(@area, page), :confirm => 'Are you sure?', :method => :delete 

%br/

= link_to 'New page', new_admin_area_page_path

app/views/admin/pages/new.haml
%h1 New Page

= error_messages_for :page

- form_tag(admin_area_pages_path(@area)) do |f| 
  = render :partial => "form"
  %p= submit_tag "Create New Page"

= link_to 'Back', admin_area_pages_path(@area)

app/views/layouts/admin.html.haml
!!!
%html
  %head
    %title= @title || "catlin design"
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
  %body.admin
    %header 
      %h1 Admin
      = link_to "Portfolio", admin_albums_path
      |
      = link_to "People", admin_people_path
      |
      = link_to "Pages", admin_areas_path
      |
      = link_to "Users", admin_users_path
      |
      = link_to "Log out", logout_path, method: :delete
    = yield

app/views/layouts/application.haml
!!!
%html
  %head
    %title= @title || "catlin design"
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    %meta{name: "viewport", content: "width=device-width, initial-scale=1"}
  %body{class: page_type}
    %header
      .logo
        %a{:href=>"/"}
      %nav
        .menu-button Menu
        %ul.items
          .links
            %li= link_to "about us", area_pages_path(Area["information"]), {:class => "information"}
            %li= link_to "designers", people_path, {:class => "people"}
            %li= link_to 'portfolio', albums_path, {:class => "albums"}
            %li= link_to 'awards', area_pages_path(Area["awards"]), {:class => "awards"}
            %li= link_to 'contact us', area_pages_path(Area["contact"]), {:class => "contact"}
    .content{:class => page_class}
      .text{:class => subnav.any? ? "thin" : "wide"}
        = yield
      - print_subnav

  <script src="http://www.google-analytics.com/urchin.js" type="text/javascript"></script>
  <script type="text/javascript">_uacct = "UA-3031369-1";urchinTracker();</script>

app/views/layouts/main.haml
!!!
%html
  %head
    %title= @title || "catlin design"
    = stylesheet_link_tag "application"
    <script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
    = javascript_include_tag "application"
    %meta{name: "viewport", content: "width=device-width, initial-scale=1"}
  %body.home
    %header
      .logo
        %a{:href=>"/"}
      %nav
        .menu-button Menu
        %ul.items
          .links
            %li= link_to "about us", area_pages_path(Area["information"]), {:class => "information"}
            %li= link_to "designers", people_path, {:class => "people"}
            %li= link_to 'portfolio', albums_path, {:class => "albums"}
            %li= link_to 'awards', area_pages_path(Area["awards"]), {:class => "awards"}
            %li= link_to 'contact us', area_pages_path(Area["contact"]), {:class => "contact"}
        .clear
    .main= yield
  <script src="http://www.google-analytics.com/urchin.js" type="text/javascript"></script>
  <script type="text/javascript">_uacct = "UA-3031369-1";urchinTracker();</script>